"""create_google_calendar_connections

Revision ID: 569d3e4cc0c6
Revises: 70f9fce354cd
Create Date: 2026-07-24 01:23:34.111409
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



revision: str = '569d3e4cc0c6'
down_revision: str | None = '70f9fce354cd'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('google_calendar_connections',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('google_account_email', sa.String(length=255), nullable=False),
    sa.Column('encrypted_refresh_token', sa.String(length=500), nullable=False),
    sa.Column('granted_scopes', sa.String(length=1000), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('token_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id')
    )
    op.create_table('google_oauth_states',
    sa.Column('state_hash', sa.String(length=255), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('state_hash')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('google_oauth_states')
    op.drop_table('google_calendar_connections')
    # ### end Alembic commands ###
