"""create_business_schedules

Revision ID: 70f9fce354cd
Revises: 7ae706e7a26d
Create Date: 2026-07-23 19:38:06.403531
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



revision: str = '70f9fce354cd'
down_revision: str | None = '7ae706e7a26d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_schedules',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('day_of_week >= 0 AND day_of_week <= 6', name='ck_business_schedules_day_range'),
    sa.CheckConstraint('is_closed = true OR (start_time IS NOT NULL AND end_time IS NOT NULL AND end_time > start_time)', name='ck_business_schedules_times'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'day_of_week', name='uq_business_schedules_day')
    )
    # ### end Alembic commands ###

    # Seed default 7-day schedule for existing businesses
    connection = op.get_bind()
    results = connection.execute(
        sa.text("SELECT id, working_start_time, working_end_time FROM businesses")
    ).fetchall()

    import uuid
    from datetime import datetime

    schedules_to_insert = []
    for row in results:
        business_id = row[0]
        working_start_time = row[1]
        working_end_time = row[2]

        for day in range(7):
            schedules_to_insert.append({
                "id": uuid.uuid4(),
                "business_id": business_id,
                "day_of_week": day,
                "start_time": working_start_time,
                "end_time": working_end_time,
                "is_closed": False,
                "created_at": datetime.now(),
                "updated_at": datetime.now(),
            })

    if schedules_to_insert:
        business_schedules_table = sa.table(
            'business_schedules',
            sa.column('id', sa.UUID),
            sa.column('business_id', sa.UUID),
            sa.column('day_of_week', sa.Integer),
            sa.column('start_time', sa.Time),
            sa.column('end_time', sa.Time),
            sa.column('is_closed', sa.Boolean),
            sa.column('created_at', sa.DateTime),
            sa.column('updated_at', sa.DateTime)
        )
        op.bulk_insert(business_schedules_table, schedules_to_insert)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('business_schedules')
    # ### end Alembic commands ###
