"""add active appointment slot index

Revision ID: 7ae706e7a26d
Revises: 20260711_01
Create Date: 2026-07-12 22:56:06.634468
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



revision: str = '7ae706e7a26d'
down_revision: str | None = '20260711_01'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_appointments_active_slot', 'appointments', ['business_id', 'appointment_date', 'start_time'], unique=True, postgresql_where=sa.text("status IN ('pending', 'confirmed')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_appointments_active_slot', table_name='appointments', postgresql_where=sa.text("status IN ('pending', 'confirmed')"))
    # ### end Alembic commands ###
