"""add_google_calendar_sync_fields_to_appointments

Revision ID: d0445db2d6cd
Revises: 569d3e4cc0c6
Create Date: 2026-07-24 16:31:18.943901
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



revision: str = 'd0445db2d6cd'
down_revision: str | None = '569d3e4cc0c6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sync_status_enum = sa.Enum('not_connected', 'pending', 'synced', 'failed', 'deleted', name='google_calendar_sync_status')
    sync_status_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('appointments', sa.Column('google_calendar_event_id', sa.String(length=255), nullable=True))
    op.add_column('appointments', sa.Column('google_calendar_sync_status', sa.Enum('not_connected', 'pending', 'synced', 'failed', 'deleted', name='google_calendar_sync_status'), server_default='not_connected', nullable=False))
    op.add_column('appointments', sa.Column('google_calendar_synced_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('appointments', sa.Column('google_calendar_last_error', sa.Text(), nullable=True))
    op.create_index(op.f('ix_appointments_google_calendar_sync_status'), 'appointments', ['google_calendar_sync_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appointments_google_calendar_sync_status'), table_name='appointments')
    op.drop_column('appointments', 'google_calendar_last_error')
    op.drop_column('appointments', 'google_calendar_synced_at')
    op.drop_column('appointments', 'google_calendar_sync_status')
    op.drop_column('appointments', 'google_calendar_event_id')

    sync_status_enum = sa.Enum('not_connected', 'pending', 'synced', 'failed', 'deleted', name='google_calendar_sync_status')
    sync_status_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
